version: "3.9"
services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    restart: always
    volumes:
      - db_data:/data/db

volumes:
  db_data: {}
